import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "ImpactAcross",
//   description: "Generated by next app",
// };

export const viewport = {
  themeColor: "#209747",
};

export const metadata = {
  metadataBase: new URL("https://impactacross.com"),
  title: {
    default: "ImpactAcross Development Research and Consultancy PLC",
    template: "%s | ImpactAcross"
  },
  description: "ImpactAcross is a dynamic development research and consultancy firm committed to transforming lives and systems across Africa. We specialize in delivering high-quality research, policy analysis, program design, monitoring & evaluation (M&E), capacity building, and strategic advisory services to NGOs, governments, development agencies, and the private sector.",
  keywords: ["impactacross", "consultancy", "development", "sustainability", "reasearch"],
  authors: [{ name: "Ketsebaot Ertumo", url: "https://ketsebaot.vercel.app" }],
  icons: {
    icon: '/logo2.png',
    apple: '/logo2.png'
  },
  openGraph: {
    title: "ImpactAcross Development Research and Consultancy PLC",
    description: "ImpactAcross is a dynamic development research and consultancy firm committed to transforming lives and systems across Africa. We specialize in delivering high-quality research, policy analysis, program design, monitoring & evaluation (M&E), capacity building, and strategic advisory services to NGOs, governments, development agencies, and the private sector.",
    url: "https://impactacross.com",
    siteName: "ImpactAcross Development Research and Consultancy PLC",
    images: [
      {
        url: "https://res.cloudinary.com/dq6mvqivd/image/upload/v1749714702/ImpactAcross/owner/logo1_ekrjmf.png",
        width: 1200,
        height: 630,
        alt: "ImpactAcross Development Research and Consultancy PLC",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "ImpactAcross Development Research and Consultancy PLC",
    description: "ImpactAcross is a dynamic development research and consultancy firm committed to transforming lives and systems across Africa. We specialize in delivering high-quality research, policy analysis, program design, monitoring & evaluation (M&E), capacity building, and strategic advisory services to NGOs, governments, development agencies, and the private sector.",
    images: [
      {
        url: "https://res.cloudinary.com/dq6mvqivd/image/upload/v1749714702/ImpactAcross/owner/logo1_ekrjmf.png",
        width: 1200,
        height: 630,
        alt: "ImpactAcross Development Research and Consultancy PLC",
      },
    ],
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ fontFamily: "var(--dynamic-font-family)" }}
      >
        {children}
        {/* <Toaster position="top-right" /> */}
        <Toaster position="top-center" />

      </body>
    </html>
  );
}
